server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: http://127.0.0.1:8081
            predicates:
              - Path=/users
              - Path=/users/
              - Path=/users/**

          - id: doctor-service
            uri: http://127.0.0.1:8082
            predicates:
              - Path=/doctors
              - Path=/doctors/
              - Path=/doctors/**

          - id: appointment-service
            uri: http://127.0.0.1:8083
            predicates:
              - Path=/appointments
              - Path=/appointments/
              - Path=/appointments/**

          - id: billing-service
            uri: http://127.0.0.1:8084
            predicates:
              - Path=/bills
              - Path=/bills/
              - Path=/bills/**
management:
  endpoints:
    web:
      exposure:
        include: health,info
