server:
  port: 8083
spring:
  application:
    name: appointment-service
user:
  service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
doctor:
  service:
    url: ${DOCTOR_SERVICE_URL:http://localhost:8082}
